name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: make install
      
      - name: Install Playwright browsers
        run: make install-browsers
      
      - name: System info
        run: make info
      
      - name: Run linter
        run: make lint
      
      - name: Run unit tests
        run: make test-unit-coverage
      
      - name: Build application for E2E tests
        run: |
          # Use custom build script that builds without launching
          node scripts/build-for-tests.js
          echo "Build complete, checking for main.js..."
          ls -la .vite/build/ || echo "Build directory not found"
      
      - name: Run E2E tests
        run: xvfb-run -a make test-e2e
        env:
          CI: true
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 7
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
      
      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: test-results
          retention-days: 7

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: make install
      
      - name: Build application
        run: make build
      
      - name: Make distributables
        run: npm run make
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/make/**/*.AppImage
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
          retention-days: 7

  # Summary job that depends on all others
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [test, build]
    if: success()
    
    steps:
      - name: CI Passed
        run: |
          echo "✅ All CI checks passed successfully!"
          echo "Test results: ✅"
          echo "Build status: ✅"