name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    
    env:
      DISPLAY: ':99'
      APPIMAGE_EXTRACT_AND_RUN: '1'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            curl \
            wget \
            git \
            build-essential \
            rpm \
            fakeroot \
            dpkg \
            zip \
            libarchive-tools \
            file \
            libfuse2 \
            desktop-file-utils \
            libgconf-2-4 \
            libgtk-3-0 \
            libgbm1 \
            libnotify4 \
            libnss3 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libatspi2.0-0 \
            libdrm2 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libasound2 \
            xvfb
        
      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
      
      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 2
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build and publish to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
      
      - name: List build artifacts
        run: |
          echo "=== Contents of out/make directory ==="
          find out/make -type f -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.zip" -o -name "*.tar.gz" | sort
        
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-linux-${{ github.ref_name }}
          path: |
            out/make/**/*.AppImage
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
          retention-days: 30